
version: 2

models:
  - name: framework_table
    description: "A table of frameworks"
    columns:
      - name: framework
        description: "Framework name"
        tests:
          - unique

  - name: framework_view
    description: "A view over framework tables"
    columns:
      - name: framework
        description: "Framework name"
        tests:
          - unique
          - not_null
